name: Renew Agentforce Dev Org Lease
run-name: ${{ github.actor }} triggered dev org renewal build
#on: [push]
on:
  schedule:
    - cron:  '30 20 * * MON'
  workflow_dispatch:
jobs:
  dev-org-renew:
    runs-on: ubuntu-latest
    environment: SFDevOrg2_AgentForce
    steps:
      - uses: actions/checkout@v4
        with: 
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: 'Install CLI'
        run: npm install @salesforce/cli --location=global
      - run: sf --version
      - name: 'Authenticate to Agentforce org'
        run: |
          echo "${{ secrets.AGENTFORCE_DEV_ORG_URL }}" > ./AGENTFORCE_DEV_ORG_URL.txt
          cat ./AGENTFORCE_DEV_ORG_URL.txt | grep -v 'force://'  # Debug without exposing full URL
          sf org login sfdx-url -f ./AGENTFORCE_DEV_ORG_URL.txt -a SFDevOrg2_AgentForce -d

      - name: 'Query data'
        run: |
            sf data query --query "select name from organization" -o UnstructuredDataAI