name: Renew Agentforce Dev Org Lease
run-name: ${{ github.actor }} triggered dev org renewal build
#on: [push]
on:
  schedule:
    - cron:  '30 20 * * MON'
  workflow_dispatch:
jobs:
  dev-org-renew:
    runs-on: ubuntu-latest
    environment: SFDevOrg2_AgentForce
    steps:
      - uses: actions/checkout@v4
        with: 
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: 'Install CLI'
        run: npm install sfdx-cli --global
      - run: sfdx --version
      
      - name: 'Debug secrets'
        run: |
          echo "Username exists: ${{ secrets.SFDEVORG2_AGENTFORCE_USERNAME != '' }}"
          echo "ClientID exists: ${{ secrets.SFDEVORG2_AGENTFORCE_CLIENTID != '' }}"
          echo "Instance URL exists: ${{ secrets.SFDEVORG2_AGENTFORCE_SF_INSTANCE_URL != '' }}"
      
      - name: 'Authenticate to Salesforce org'
        run: |
          # Set explicit variables first
          USERNAME="${{ secrets.SFDEVORG2_AGENTFORCE_USERNAME }}"
          CLIENTID="${{ secrets.SFDEVORG2_AGENTFORCE_CLIENTID }}"
          INSTANCEURL="${{ secrets.SFDEVORG2_AGENTFORCE_SF_INSTANCE_URL }}"
          
          # Check if username is set properly
          echo "Using username: $USERNAME"
          
          # Run the command with explicit variables
          sfdx force:auth:jwt:grant \
            --clientid "$CLIENTID" \
            --jwtkeyfile server.key \
            --username "$USERNAME" \
            --instanceurl "$INSTANCEURL" \
            --setalias SFDevOrg2_AgentForce \
            --setdefaultdevhubusername

      - name: 'Query data to verify connection'
        run: |
            sfdx force:data:soql:query --query "select name from organization" --targetusername SFDevOrg2_AgentForce